"""Comprehensive ISO 3166-1 alpha-3 country metadata.

Maps ISO_A3 codes to display names and ISO_A2 codes used by news APIs.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class CountryInfo:
    name: str
    iso_a2: str


COUNTRIES: dict[str, CountryInfo] = {
    "AFG": CountryInfo("Afghanistan", "af"),
    "ALB": CountryInfo("Albania", "al"),
    "DZA": CountryInfo("Algeria", "dz"),
    "AND": CountryInfo("Andorra", "ad"),
    "AGO": CountryInfo("Angola", "ao"),
    "ATG": CountryInfo("Antigua and Barbuda", "ag"),
    "ARG": CountryInfo("Argentina", "ar"),
    "ARM": CountryInfo("Armenia", "am"),
    "AUS": CountryInfo("Australia", "au"),
    "AUT": CountryInfo("Austria", "at"),
    "AZE": CountryInfo("Azerbaijan", "az"),
    "BHS": CountryInfo("Bahamas", "bs"),
    "BHR": CountryInfo("Bahrain", "bh"),
    "BGD": CountryInfo("Bangladesh", "bd"),
    "BRB": CountryInfo("Barbados", "bb"),
    "BLR": CountryInfo("Belarus", "by"),
    "BEL": CountryInfo("Belgium", "be"),
    "BLZ": CountryInfo("Belize", "bz"),
    "BEN": CountryInfo("Benin", "bj"),
    "BTN": CountryInfo("Bhutan", "bt"),
    "BOL": CountryInfo("Bolivia", "bo"),
    "BIH": CountryInfo("Bosnia and Herzegovina", "ba"),
    "BWA": CountryInfo("Botswana", "bw"),
    "BRA": CountryInfo("Brazil", "br"),
    "BRN": CountryInfo("Brunei", "bn"),
    "BGR": CountryInfo("Bulgaria", "bg"),
    "BFA": CountryInfo("Burkina Faso", "bf"),
    "BDI": CountryInfo("Burundi", "bi"),
    "KHM": CountryInfo("Cambodia", "kh"),
    "CMR": CountryInfo("Cameroon", "cm"),
    "CAN": CountryInfo("Canada", "ca"),
    "CPV": CountryInfo("Cape Verde", "cv"),
    "CAF": CountryInfo("Central African Republic", "cf"),
    "TCD": CountryInfo("Chad", "td"),
    "CHL": CountryInfo("Chile", "cl"),
    "CHN": CountryInfo("China", "cn"),
    "COL": CountryInfo("Colombia", "co"),
    "COM": CountryInfo("Comoros", "km"),
    "COG": CountryInfo("Republic of the Congo", "cg"),
    "COD": CountryInfo("Democratic Republic of the Congo", "cd"),
    "CRI": CountryInfo("Costa Rica", "cr"),
    "CIV": CountryInfo("Côte d'Ivoire", "ci"),
    "HRV": CountryInfo("Croatia", "hr"),
    "CUB": CountryInfo("Cuba", "cu"),
    "CYP": CountryInfo("Cyprus", "cy"),
    "CZE": CountryInfo("Czech Republic", "cz"),
    "DNK": CountryInfo("Denmark", "dk"),
    "DJI": CountryInfo("Djibouti", "dj"),
    "DMA": CountryInfo("Dominica", "dm"),
    "DOM": CountryInfo("Dominican Republic", "do"),
    "ECU": CountryInfo("Ecuador", "ec"),
    "EGY": CountryInfo("Egypt", "eg"),
    "SLV": CountryInfo("El Salvador", "sv"),
    "GNQ": CountryInfo("Equatorial Guinea", "gq"),
    "ERI": CountryInfo("Eritrea", "er"),
    "EST": CountryInfo("Estonia", "ee"),
    "SWZ": CountryInfo("Eswatini", "sz"),
    "ETH": CountryInfo("Ethiopia", "et"),
    "FJI": CountryInfo("Fiji", "fj"),
    "FIN": CountryInfo("Finland", "fi"),
    "FRA": CountryInfo("France", "fr"),
    "GAB": CountryInfo("Gabon", "ga"),
    "GMB": CountryInfo("Gambia", "gm"),
    "GEO": CountryInfo("Georgia", "ge"),
    "DEU": CountryInfo("Germany", "de"),
    "GHA": CountryInfo("Ghana", "gh"),
    "GRC": CountryInfo("Greece", "gr"),
    "GRD": CountryInfo("Grenada", "gd"),
    "GTM": CountryInfo("Guatemala", "gt"),
    "GIN": CountryInfo("Guinea", "gn"),
    "GNB": CountryInfo("Guinea-Bissau", "gw"),
    "GUY": CountryInfo("Guyana", "gy"),
    "HTI": CountryInfo("Haiti", "ht"),
    "HND": CountryInfo("Honduras", "hn"),
    "HUN": CountryInfo("Hungary", "hu"),
    "ISL": CountryInfo("Iceland", "is"),
    "IND": CountryInfo("India", "in"),
    "IDN": CountryInfo("Indonesia", "id"),
    "IRN": CountryInfo("Iran", "ir"),
    "IRQ": CountryInfo("Iraq", "iq"),
    "IRL": CountryInfo("Ireland", "ie"),
    "ISR": CountryInfo("Israel", "il"),
    "ITA": CountryInfo("Italy", "it"),
    "JAM": CountryInfo("Jamaica", "jm"),
    "JPN": CountryInfo("Japan", "jp"),
    "JOR": CountryInfo("Jordan", "jo"),
    "KAZ": CountryInfo("Kazakhstan", "kz"),
    "KEN": CountryInfo("Kenya", "ke"),
    "KIR": CountryInfo("Kiribati", "ki"),
    "PRK": CountryInfo("North Korea", "kp"),
    "KOR": CountryInfo("South Korea", "kr"),
    "KWT": CountryInfo("Kuwait", "kw"),
    "KGZ": CountryInfo("Kyrgyzstan", "kg"),
    "LAO": CountryInfo("Laos", "la"),
    "LVA": CountryInfo("Latvia", "lv"),
    "LBN": CountryInfo("Lebanon", "lb"),
    "LSO": CountryInfo("Lesotho", "ls"),
    "LBR": CountryInfo("Liberia", "lr"),
    "LBY": CountryInfo("Libya", "ly"),
    "LIE": CountryInfo("Liechtenstein", "li"),
    "LTU": CountryInfo("Lithuania", "lt"),
    "LUX": CountryInfo("Luxembourg", "lu"),
    "MDG": CountryInfo("Madagascar", "mg"),
    "MWI": CountryInfo("Malawi", "mw"),
    "MYS": CountryInfo("Malaysia", "my"),
    "MDV": CountryInfo("Maldives", "mv"),
    "MLI": CountryInfo("Mali", "ml"),
    "MLT": CountryInfo("Malta", "mt"),
    "MHL": CountryInfo("Marshall Islands", "mh"),
    "MRT": CountryInfo("Mauritania", "mr"),
    "MUS": CountryInfo("Mauritius", "mu"),
    "MEX": CountryInfo("Mexico", "mx"),
    "FSM": CountryInfo("Micronesia", "fm"),
    "MDA": CountryInfo("Moldova", "md"),
    "MCO": CountryInfo("Monaco", "mc"),
    "MNG": CountryInfo("Mongolia", "mn"),
    "MNE": CountryInfo("Montenegro", "me"),
    "MAR": CountryInfo("Morocco", "ma"),
    "MOZ": CountryInfo("Mozambique", "mz"),
    "MMR": CountryInfo("Myanmar", "mm"),
    "NAM": CountryInfo("Namibia", "na"),
    "NRU": CountryInfo("Nauru", "nr"),
    "NPL": CountryInfo("Nepal", "np"),
    "NLD": CountryInfo("Netherlands", "nl"),
    "NZL": CountryInfo("New Zealand", "nz"),
    "NIC": CountryInfo("Nicaragua", "ni"),
    "NER": CountryInfo("Niger", "ne"),
    "NGA": CountryInfo("Nigeria", "ng"),
    "MKD": CountryInfo("North Macedonia", "mk"),
    "NOR": CountryInfo("Norway", "no"),
    "OMN": CountryInfo("Oman", "om"),
    "PAK": CountryInfo("Pakistan", "pk"),
    "PLW": CountryInfo("Palau", "pw"),
    "PSE": CountryInfo("Palestine", "ps"),
    "PAN": CountryInfo("Panama", "pa"),
    "PNG": CountryInfo("Papua New Guinea", "pg"),
    "PRY": CountryInfo("Paraguay", "py"),
    "PER": CountryInfo("Peru", "pe"),
    "PHL": CountryInfo("Philippines", "ph"),
    "POL": CountryInfo("Poland", "pl"),
    "PRT": CountryInfo("Portugal", "pt"),
    "QAT": CountryInfo("Qatar", "qa"),
    "ROU": CountryInfo("Romania", "ro"),
    "RUS": CountryInfo("Russia", "ru"),
    "RWA": CountryInfo("Rwanda", "rw"),
    "KNA": CountryInfo("Saint Kitts and Nevis", "kn"),
    "LCA": CountryInfo("Saint Lucia", "lc"),
    "VCT": CountryInfo("Saint Vincent and the Grenadines", "vc"),
    "WSM": CountryInfo("Samoa", "ws"),
    "SMR": CountryInfo("San Marino", "sm"),
    "STP": CountryInfo("São Tomé and Príncipe", "st"),
    "SAU": CountryInfo("Saudi Arabia", "sa"),
    "SEN": CountryInfo("Senegal", "sn"),
    "SRB": CountryInfo("Serbia", "rs"),
    "SYC": CountryInfo("Seychelles", "sc"),
    "SLE": CountryInfo("Sierra Leone", "sl"),
    "SGP": CountryInfo("Singapore", "sg"),
    "SVK": CountryInfo("Slovakia", "sk"),
    "SVN": CountryInfo("Slovenia", "si"),
    "SLB": CountryInfo("Solomon Islands", "sb"),
    "SOM": CountryInfo("Somalia", "so"),
    "ZAF": CountryInfo("South Africa", "za"),
    "SSD": CountryInfo("South Sudan", "ss"),
    "ESP": CountryInfo("Spain", "es"),
    "LKA": CountryInfo("Sri Lanka", "lk"),
    "SDN": CountryInfo("Sudan", "sd"),
    "SUR": CountryInfo("Suriname", "sr"),
    "SWE": CountryInfo("Sweden", "se"),
    "CHE": CountryInfo("Switzerland", "ch"),
    "SYR": CountryInfo("Syria", "sy"),
    "TWN": CountryInfo("Taiwan", "tw"),
    "TJK": CountryInfo("Tajikistan", "tj"),
    "TZA": CountryInfo("Tanzania", "tz"),
    "THA": CountryInfo("Thailand", "th"),
    "TLS": CountryInfo("Timor-Leste", "tl"),
    "TGO": CountryInfo("Togo", "tg"),
    "TON": CountryInfo("Tonga", "to"),
    "TTO": CountryInfo("Trinidad and Tobago", "tt"),
    "TUN": CountryInfo("Tunisia", "tn"),
    "TUR": CountryInfo("Turkey", "tr"),
    "TKM": CountryInfo("Turkmenistan", "tm"),
    "TUV": CountryInfo("Tuvalu", "tv"),
    "UGA": CountryInfo("Uganda", "ug"),
    "UKR": CountryInfo("Ukraine", "ua"),
    "ARE": CountryInfo("United Arab Emirates", "ae"),
    "GBR": CountryInfo("United Kingdom", "gb"),
    "USA": CountryInfo("United States", "us"),
    "URY": CountryInfo("Uruguay", "uy"),
    "UZB": CountryInfo("Uzbekistan", "uz"),
    "VUT": CountryInfo("Vanuatu", "vu"),
    "VAT": CountryInfo("Vatican City", "va"),
    "VEN": CountryInfo("Venezuela", "ve"),
    "VNM": CountryInfo("Vietnam", "vn"),
    "YEM": CountryInfo("Yemen", "ye"),
    "ZMB": CountryInfo("Zambia", "zm"),
    "ZWE": CountryInfo("Zimbabwe", "zw"),
    # Territories and special regions often found in map tiles
    "XKX": CountryInfo("Kosovo", "xk"),
    "GRL": CountryInfo("Greenland", "gl"),
    "NCL": CountryInfo("New Caledonia", "nc"),
    "PRI": CountryInfo("Puerto Rico", "pr"),
    "GUF": CountryInfo("French Guiana", "gf"),
    "REU": CountryInfo("Réunion", "re"),
    "MTQ": CountryInfo("Martinique", "mq"),
    "GLP": CountryInfo("Guadeloupe", "gp"),
    "MYT": CountryInfo("Mayotte", "yt"),
    "HKG": CountryInfo("Hong Kong", "hk"),
    "MAC": CountryInfo("Macau", "mo"),
    "FLK": CountryInfo("Falkland Islands", "fk"),
    "FRO": CountryInfo("Faroe Islands", "fo"),
    "SJM": CountryInfo("Svalbard and Jan Mayen", "sj"),
    "CUW": CountryInfo("Curaçao", "cw"),
    "ABW": CountryInfo("Aruba", "aw"),
    "SXM": CountryInfo("Sint Maarten", "sx"),
    "CYM": CountryInfo("Cayman Islands", "ky"),
    "BMU": CountryInfo("Bermuda", "bm"),
    "GIB": CountryInfo("Gibraltar", "gi"),
    "TCA": CountryInfo("Turks and Caicos Islands", "tc"),
    "VGB": CountryInfo("British Virgin Islands", "vg"),
    "AIA": CountryInfo("Anguilla", "ai"),
    "MSR": CountryInfo("Montserrat", "ms"),
    "SHN": CountryInfo("Saint Helena", "sh"),
    "WLF": CountryInfo("Wallis and Futuna", "wf"),
    "SPM": CountryInfo("Saint Pierre and Miquelon", "pm"),
    "PCN": CountryInfo("Pitcairn Islands", "pn"),
}

# Legacy compat — flat dict for quick name lookups
COUNTRY_LOOKUP: dict[str, str] = {code: info.name for code, info in COUNTRIES.items()}


def get_country_name(iso_a3: str) -> str:
    """Return the display name for an ISO_A3 code, or the code itself as fallback."""
    info = COUNTRIES.get(iso_a3.upper())
    return info.name if info else iso_a3


def get_iso_a2(iso_a3: str) -> str:
    """Return the ISO_A2 code for news API queries. Falls back to lowercase A3 slice."""
    info = COUNTRIES.get(iso_a3.upper())
    return info.iso_a2 if info else iso_a3[:2].lower()
