"""Comprehensive ISO 3166-1 alpha-3 country metadata.

Maps ISO_A3 codes to display names, ISO_A2 codes, and enriched knowledge-base
fields used by the news ingestion and relevance-scoring pipelines.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class CountryInfo:
    name: str
    iso_a2: str
    capital: str = ""
    leader_titles: tuple[str, ...] = ()
    key_ministries: tuple[str, ...] = ()
    regions: tuple[str, ...] = ()
    demonyms: tuple[str, ...] = ()
    aliases: tuple[str, ...] = ()
    major_cities: tuple[str, ...] = ()
    key_entities: tuple[str, ...] = ()


# ---------------------------------------------------------------------------
# Full country table.  High-priority countries (G20 + conflict zones + major
# geopolitical actors) are enriched with knowledge-base fields.  Lower-priority
# entries have the bare minimum (name + iso_a2) and can be enriched later.
# ---------------------------------------------------------------------------

COUNTRIES: dict[str, CountryInfo] = {
    # ── ENRICHED COUNTRIES (40+) ──────────────────────────────────────────
    "USA": CountryInfo(
        "United States", "us",
        capital="Washington, D.C.",
        leader_titles=("President",),
        key_ministries=("State Department", "Department of Defense", "Treasury Department", "Department of Justice"),
        regions=("California", "Texas", "Florida", "New York", "Illinois", "Pennsylvania", "Ohio", "Georgia"),
        demonyms=("American", "Americans"),
        aliases=("United States", "U.S.", "US", "U.S.A.", "America"),
        major_cities=("Washington", "Washington DC", "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "San Francisco", "Seattle", "Miami"),
        key_entities=("White House", "Congress", "Pentagon", "Supreme Court", "Federal Reserve", "CIA", "FBI", "NSA", "Senate", "House of Representatives"),
    ),
    "GBR": CountryInfo(
        "United Kingdom", "gb",
        capital="London",
        leader_titles=("Prime Minister", "King"),
        key_ministries=("Foreign Office", "Home Office", "Ministry of Defence", "Treasury"),
        regions=("England", "Scotland", "Wales", "Northern Ireland"),
        demonyms=("British", "Briton", "Britons"),
        aliases=("United Kingdom", "U.K.", "UK", "Britain", "Great Britain"),
        major_cities=("London", "Manchester", "Birmingham", "Edinburgh", "Glasgow", "Liverpool", "Leeds", "Bristol"),
        key_entities=("Downing Street", "Westminster", "Parliament", "House of Commons", "House of Lords", "MI5", "MI6", "Bank of England"),
    ),
    "IND": CountryInfo(
        "India", "in",
        capital="New Delhi",
        leader_titles=("Prime Minister", "President"),
        key_ministries=("Ministry of External Affairs", "Ministry of Defence", "Ministry of Finance", "Ministry of Home Affairs"),
        regions=("Uttar Pradesh", "Maharashtra", "Tamil Nadu", "Karnataka", "West Bengal", "Rajasthan", "Gujarat", "Kerala", "Punjab", "Bihar"),
        demonyms=("Indian", "Indians"),
        aliases=("India", "Bharat", "Republic of India"),
        major_cities=("New Delhi", "Delhi", "Mumbai", "Bengaluru", "Bangalore", "Chennai", "Kolkata", "Hyderabad", "Pune", "Ahmedabad", "Jaipur"),
        key_entities=("Lok Sabha", "Rajya Sabha", "Supreme Court of India", "RBI", "Reserve Bank of India", "ISRO", "Parliament of India"),
    ),
    "CHN": CountryInfo(
        "China", "cn",
        capital="Beijing",
        leader_titles=("President", "Premier", "General Secretary"),
        key_ministries=("Ministry of Foreign Affairs", "Ministry of National Defense", "Ministry of Commerce"),
        regions=("Guangdong", "Shandong", "Henan", "Sichuan", "Jiangsu", "Zhejiang", "Xinjiang", "Tibet"),
        demonyms=("Chinese",),
        aliases=("China", "People's Republic of China", "PRC"),
        major_cities=("Beijing", "Shanghai", "Shenzhen", "Guangzhou", "Chengdu", "Wuhan", "Hangzhou", "Nanjing", "Tianjin", "Xi'an"),
        key_entities=("CPC", "CCP", "Communist Party", "Politburo", "NPC", "National People's Congress", "PLA", "People's Liberation Army"),
    ),
    "RUS": CountryInfo(
        "Russia", "ru",
        capital="Moscow",
        leader_titles=("President", "Prime Minister"),
        key_ministries=("Ministry of Defence", "Ministry of Foreign Affairs", "Ministry of Finance"),
        regions=("Crimea", "Siberia", "Chechnya", "Dagestan", "Tatarstan", "Kaliningrad"),
        demonyms=("Russian", "Russians"),
        aliases=("Russia", "Russian Federation"),
        major_cities=("Moscow", "St Petersburg", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Vladivostok", "Sochi"),
        key_entities=("Kremlin", "Duma", "State Duma", "Federal Assembly", "FSB", "GRU", "Roscosmos"),
    ),
    "FRA": CountryInfo(
        "France", "fr",
        capital="Paris",
        leader_titles=("President", "Prime Minister"),
        key_ministries=("Ministry of Foreign Affairs", "Ministry of the Armed Forces", "Ministry of the Economy"),
        regions=("Île-de-France", "Provence", "Occitanie", "Normandy", "Brittany", "Corsica"),
        demonyms=("French",),
        aliases=("France", "French Republic"),
        major_cities=("Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Bordeaux"),
        key_entities=("Élysée", "Elysee", "National Assembly", "Senate", "Matignon"),
    ),
    "DEU": CountryInfo(
        "Germany", "de",
        capital="Berlin",
        leader_titles=("Chancellor", "President"),
        key_ministries=("Federal Foreign Office", "Federal Ministry of Defence", "Federal Ministry of Finance"),
        regions=("Bavaria", "North Rhine-Westphalia", "Baden-Württemberg", "Lower Saxony", "Hesse", "Saxony"),
        demonyms=("German", "Germans"),
        aliases=("Germany", "Federal Republic of Germany"),
        major_cities=("Berlin", "Munich", "Frankfurt", "Hamburg", "Cologne", "Stuttgart", "Düsseldorf", "Dresden"),
        key_entities=("Bundestag", "Bundesrat", "Bundeswehr", "Bundesbank"),
    ),
    "JPN": CountryInfo(
        "Japan", "jp",
        capital="Tokyo",
        leader_titles=("Prime Minister", "Emperor"),
        key_ministries=("Ministry of Foreign Affairs", "Ministry of Defense", "Ministry of Finance"),
        regions=("Hokkaido", "Kanto", "Kansai", "Kyushu", "Tohoku", "Okinawa"),
        demonyms=("Japanese",),
        aliases=("Japan",),
        major_cities=("Tokyo", "Osaka", "Yokohama", "Nagoya", "Kyoto", "Fukuoka", "Sapporo", "Kobe", "Hiroshima"),
        key_entities=("Diet", "JSDF", "Bank of Japan", "METI", "Imperial Palace"),
    ),
    "KOR": CountryInfo(
        "South Korea", "kr",
        capital="Seoul",
        leader_titles=("President", "Prime Minister"),
        key_ministries=("Ministry of Foreign Affairs", "Ministry of National Defense"),
        regions=("Gyeonggi", "Gangwon", "Jeolla", "Gyeongsang"),
        demonyms=("South Korean", "Korean", "Koreans"),
        aliases=("South Korea", "Republic of Korea", "ROK"),
        major_cities=("Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Ulsan"),
        key_entities=("National Assembly", "Blue House", "Yongsan"),
    ),
    "PRK": CountryInfo(
        "North Korea", "kp",
        capital="Pyongyang",
        leader_titles=("Supreme Leader", "Chairman"),
        key_ministries=(),
        regions=(),
        demonyms=("North Korean",),
        aliases=("North Korea", "DPRK", "Democratic People's Republic of Korea"),
        major_cities=("Pyongyang", "Kaesong"),
        key_entities=("Workers' Party", "Korean People's Army", "KPA"),
    ),
    "ARE": CountryInfo(
        "United Arab Emirates", "ae",
        capital="Abu Dhabi",
        leader_titles=("President", "Prime Minister", "Crown Prince"),
        key_ministries=("Ministry of Foreign Affairs",),
        regions=("Abu Dhabi", "Dubai", "Sharjah", "Ajman", "Ras Al Khaimah"),
        demonyms=("Emirati", "Emiratis"),
        aliases=("United Arab Emirates", "UAE", "U.A.E."),
        major_cities=("Abu Dhabi", "Dubai", "Sharjah"),
        key_entities=("ADNOC", "Emirates", "Masdar"),
    ),
    "SAU": CountryInfo(
        "Saudi Arabia", "sa",
        capital="Riyadh",
        leader_titles=("King", "Crown Prince", "Prime Minister"),
        key_ministries=("Ministry of Foreign Affairs", "Ministry of Defense"),
        regions=("Riyadh Province", "Makkah Province", "Eastern Province"),
        demonyms=("Saudi", "Saudis"),
        aliases=("Saudi Arabia", "KSA", "Kingdom of Saudi Arabia"),
        major_cities=("Riyadh", "Jeddah", "Mecca", "Medina", "Dammam"),
        key_entities=("Saudi Aramco", "NEOM", "Vision 2030", "Shura Council"),
    ),
    "ISR": CountryInfo(
        "Israel", "il",
        capital="Jerusalem",
        leader_titles=("Prime Minister", "President"),
        key_ministries=("Ministry of Defense", "Ministry of Foreign Affairs"),
        regions=("Negev", "Galilee", "West Bank", "Golan Heights"),
        demonyms=("Israeli", "Israelis"),
        aliases=("Israel", "State of Israel"),
        major_cities=("Jerusalem", "Tel Aviv", "Haifa", "Beer Sheva"),
        key_entities=("Knesset", "IDF", "Mossad", "Shin Bet"),
    ),
    "IRN": CountryInfo(
        "Iran", "ir",
        capital="Tehran",
        leader_titles=("Supreme Leader", "President"),
        key_ministries=("Ministry of Foreign Affairs", "Ministry of Defence"),
        regions=("Tehran Province", "Isfahan Province", "Fars Province", "Khuzestan Province"),
        demonyms=("Iranian", "Iranians"),
        aliases=("Iran", "Islamic Republic of Iran", "Persia"),
        major_cities=("Tehran", "Isfahan", "Mashhad", "Tabriz", "Shiraz"),
        key_entities=("IRGC", "Revolutionary Guard", "Guardian Council", "Majlis"),
    ),
    "TUR": CountryInfo(
        "Turkey", "tr",
        capital="Ankara",
        leader_titles=("President",),
        key_ministries=("Ministry of Foreign Affairs", "Ministry of National Defence"),
        regions=("Marmara", "Aegean", "Central Anatolia", "Eastern Anatolia", "Southeastern Anatolia"),
        demonyms=("Turkish", "Turks"),
        aliases=("Turkey", "Türkiye", "Republic of Turkey", "Republic of Türkiye"),
        major_cities=("Ankara", "Istanbul", "Izmir", "Antalya", "Bursa"),
        key_entities=("Grand National Assembly", "AKP", "CHP"),
    ),
    "EGY": CountryInfo(
        "Egypt", "eg",
        capital="Cairo",
        leader_titles=("President",),
        key_ministries=("Ministry of Foreign Affairs", "Ministry of Defence"),
        regions=("Upper Egypt", "Lower Egypt", "Sinai"),
        demonyms=("Egyptian", "Egyptians"),
        aliases=("Egypt", "Arab Republic of Egypt"),
        major_cities=("Cairo", "Alexandria", "Giza", "Luxor", "Aswan"),
        key_entities=("Suez Canal", "Al-Azhar"),
    ),
    "BRA": CountryInfo(
        "Brazil", "br",
        capital="Brasília",
        leader_titles=("President",),
        key_ministries=("Ministry of Foreign Affairs", "Ministry of Defence", "Ministry of Finance"),
        regions=("São Paulo", "Rio de Janeiro", "Minas Gerais", "Bahia", "Amazonas"),
        demonyms=("Brazilian", "Brazilians"),
        aliases=("Brazil", "Brasil", "Federative Republic of Brazil"),
        major_cities=("Brasília", "São Paulo", "Rio de Janeiro", "Salvador", "Belo Horizonte", "Manaus", "Recife"),
        key_entities=("Planalto", "National Congress", "Petrobras"),
    ),
    "MEX": CountryInfo(
        "Mexico", "mx",
        capital="Mexico City",
        leader_titles=("President",),
        key_ministries=("Ministry of Foreign Affairs",),
        regions=("Jalisco", "Nuevo León", "Chiapas", "Oaxaca"),
        demonyms=("Mexican", "Mexicans"),
        aliases=("Mexico", "México", "United Mexican States"),
        major_cities=("Mexico City", "Guadalajara", "Monterrey", "Puebla", "Cancún", "Tijuana"),
        key_entities=("Chamber of Deputies", "Senate", "PEMEX"),
    ),
    "CAN": CountryInfo(
        "Canada", "ca",
        capital="Ottawa",
        leader_titles=("Prime Minister",),
        key_ministries=("Global Affairs Canada", "Department of National Defence"),
        regions=("Ontario", "Quebec", "British Columbia", "Alberta", "Manitoba", "Saskatchewan"),
        demonyms=("Canadian", "Canadians"),
        aliases=("Canada",),
        major_cities=("Ottawa", "Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Winnipeg"),
        key_entities=("Parliament", "House of Commons", "Senate", "Bank of Canada", "RCMP"),
    ),
    "AUS": CountryInfo(
        "Australia", "au",
        capital="Canberra",
        leader_titles=("Prime Minister",),
        key_ministries=("Department of Foreign Affairs and Trade", "Department of Defence"),
        regions=("New South Wales", "Victoria", "Queensland", "Western Australia", "South Australia", "Tasmania"),
        demonyms=("Australian", "Australians"),
        aliases=("Australia",),
        major_cities=("Canberra", "Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"),
        key_entities=("Parliament House", "Reserve Bank of Australia", "ASIO", "ADF"),
    ),
    "IDN": CountryInfo(
        "Indonesia", "id",
        capital="Jakarta",
        leader_titles=("President",),
        key_ministries=("Ministry of Foreign Affairs", "Ministry of Defence"),
        regions=("Java", "Sumatra", "Kalimantan", "Sulawesi", "Papua", "Bali"),
        demonyms=("Indonesian", "Indonesians"),
        aliases=("Indonesia", "Republic of Indonesia"),
        major_cities=("Jakarta", "Surabaya", "Bandung", "Medan", "Bali", "Yogyakarta"),
        key_entities=("DPR", "People's Consultative Assembly", "TNI"),
    ),
    "PAK": CountryInfo(
        "Pakistan", "pk",
        capital="Islamabad",
        leader_titles=("Prime Minister", "President"),
        key_ministries=("Ministry of Foreign Affairs", "Ministry of Defence"),
        regions=("Punjab", "Sindh", "Khyber Pakhtunkhwa", "Balochistan", "Gilgit-Baltistan"),
        demonyms=("Pakistani", "Pakistanis"),
        aliases=("Pakistan", "Islamic Republic of Pakistan"),
        major_cities=("Islamabad", "Karachi", "Lahore", "Peshawar", "Quetta", "Faisalabad", "Rawalpindi"),
        key_entities=("National Assembly", "Senate", "ISI", "Pakistan Army"),
    ),
    "NGA": CountryInfo(
        "Nigeria", "ng",
        capital="Abuja",
        leader_titles=("President",),
        key_ministries=("Ministry of Foreign Affairs", "Ministry of Defence"),
        regions=("Lagos", "Kano", "Rivers", "Oyo", "Kaduna", "Borno"),
        demonyms=("Nigerian", "Nigerians"),
        aliases=("Nigeria", "Federal Republic of Nigeria"),
        major_cities=("Abuja", "Lagos", "Kano", "Ibadan", "Port Harcourt"),
        key_entities=("National Assembly", "NNPC"),
    ),
    "ZAF": CountryInfo(
        "South Africa", "za",
        capital="Pretoria",
        leader_titles=("President",),
        key_ministries=("Department of International Relations",),
        regions=("Gauteng", "Western Cape", "KwaZulu-Natal", "Eastern Cape"),
        demonyms=("South African", "South Africans"),
        aliases=("South Africa", "RSA", "Republic of South Africa"),
        major_cities=("Pretoria", "Johannesburg", "Cape Town", "Durban"),
        key_entities=("Parliament", "ANC", "National Assembly", "Constitutional Court"),
    ),
    "UKR": CountryInfo(
        "Ukraine", "ua",
        capital="Kyiv",
        leader_titles=("President",),
        key_ministries=("Ministry of Foreign Affairs", "Ministry of Defence"),
        regions=("Donetsk", "Luhansk", "Crimea", "Kherson", "Zaporizhzhia", "Kharkiv", "Odesa"),
        demonyms=("Ukrainian", "Ukrainians"),
        aliases=("Ukraine",),
        major_cities=("Kyiv", "Kiev", "Kharkiv", "Odesa", "Odessa", "Dnipro", "Lviv", "Zaporizhzhia"),
        key_entities=("Verkhovna Rada", "Armed Forces of Ukraine", "ZSU"),
    ),
    "POL": CountryInfo(
        "Poland", "pl",
        capital="Warsaw",
        leader_titles=("President", "Prime Minister"),
        key_ministries=("Ministry of Foreign Affairs", "Ministry of National Defence"),
        regions=("Masovia", "Lesser Poland", "Silesia"),
        demonyms=("Polish", "Poles"),
        aliases=("Poland", "Republic of Poland"),
        major_cities=("Warsaw", "Krakow", "Łódź", "Wrocław", "Gdańsk", "Poznań"),
        key_entities=("Sejm", "Senate"),
    ),
    "ITA": CountryInfo(
        "Italy", "it",
        capital="Rome",
        leader_titles=("Prime Minister", "President"),
        key_ministries=("Ministry of Foreign Affairs", "Ministry of Defence"),
        regions=("Lombardy", "Lazio", "Campania", "Sicily", "Veneto", "Tuscany"),
        demonyms=("Italian", "Italians"),
        aliases=("Italy", "Italian Republic"),
        major_cities=("Rome", "Milan", "Naples", "Turin", "Florence", "Venice", "Bologna"),
        key_entities=("Palazzo Chigi", "Chamber of Deputies", "Senate"),
    ),
    "ESP": CountryInfo(
        "Spain", "es",
        capital="Madrid",
        leader_titles=("Prime Minister", "King"),
        key_ministries=("Ministry of Foreign Affairs",),
        regions=("Catalonia", "Andalusia", "Madrid", "Basque Country", "Valencia", "Galicia"),
        demonyms=("Spanish", "Spaniard", "Spaniards"),
        aliases=("Spain", "Kingdom of Spain", "España"),
        major_cities=("Madrid", "Barcelona", "Valencia", "Seville", "Bilbao", "Málaga"),
        key_entities=("Cortes Generales", "Moncloa"),
    ),
    "ARG": CountryInfo(
        "Argentina", "ar",
        capital="Buenos Aires",
        leader_titles=("President",),
        key_ministries=("Ministry of Foreign Affairs",),
        regions=("Buenos Aires Province", "Córdoba", "Santa Fe", "Mendoza", "Patagonia"),
        demonyms=("Argentine", "Argentinian", "Argentinians"),
        aliases=("Argentina", "Argentine Republic"),
        major_cities=("Buenos Aires", "Córdoba", "Rosario", "Mendoza"),
        key_entities=("Casa Rosada", "National Congress"),
    ),
    "COL": CountryInfo(
        "Colombia", "co",
        capital="Bogotá",
        leader_titles=("President",),
        key_ministries=("Ministry of Foreign Affairs",),
        regions=("Antioquia", "Valle del Cauca", "Cundinamarca"),
        demonyms=("Colombian", "Colombians"),
        aliases=("Colombia", "Republic of Colombia"),
        major_cities=("Bogotá", "Medellín", "Cali", "Cartagena", "Barranquilla"),
        key_entities=("Congress", "Casa de Nariño"),
    ),
    "THA": CountryInfo(
        "Thailand", "th",
        capital="Bangkok",
        leader_titles=("Prime Minister", "King"),
        key_ministries=("Ministry of Foreign Affairs",),
        regions=("Bangkok", "Chiang Mai", "Phuket", "Isan"),
        demonyms=("Thai", "Thais"),
        aliases=("Thailand", "Kingdom of Thailand"),
        major_cities=("Bangkok", "Chiang Mai", "Pattaya", "Phuket"),
        key_entities=("National Assembly", "Royal Thai Armed Forces"),
    ),
    "VNM": CountryInfo(
        "Vietnam", "vn",
        capital="Hanoi",
        leader_titles=("President", "Prime Minister", "General Secretary"),
        key_ministries=("Ministry of Foreign Affairs",),
        regions=(),
        demonyms=("Vietnamese",),
        aliases=("Vietnam", "Viet Nam", "Socialist Republic of Vietnam"),
        major_cities=("Hanoi", "Ho Chi Minh City", "Saigon", "Da Nang"),
        key_entities=("National Assembly", "CPV", "Communist Party"),
    ),
    "PHL": CountryInfo(
        "Philippines", "ph",
        capital="Manila",
        leader_titles=("President",),
        key_ministries=("Department of Foreign Affairs",),
        regions=("Luzon", "Visayas", "Mindanao"),
        demonyms=("Filipino", "Filipinos", "Philippine"),
        aliases=("Philippines", "Republic of the Philippines"),
        major_cities=("Manila", "Quezon City", "Cebu", "Davao"),
        key_entities=("Congress", "Senate", "Malacañang"),
    ),
    "MYS": CountryInfo(
        "Malaysia", "my",
        capital="Kuala Lumpur",
        leader_titles=("Prime Minister", "King"),
        key_ministries=("Ministry of Foreign Affairs",),
        regions=("Selangor", "Johor", "Sabah", "Sarawak", "Penang"),
        demonyms=("Malaysian", "Malaysians"),
        aliases=("Malaysia",),
        major_cities=("Kuala Lumpur", "Johor Bahru", "George Town", "Kota Kinabalu"),
        key_entities=("Parliament", "Petronas"),
    ),
    "SGP": CountryInfo(
        "Singapore", "sg",
        capital="Singapore",
        leader_titles=("Prime Minister", "President"),
        key_ministries=("Ministry of Foreign Affairs", "Ministry of Defence"),
        regions=(),
        demonyms=("Singaporean", "Singaporeans"),
        aliases=("Singapore", "Republic of Singapore"),
        major_cities=("Singapore",),
        key_entities=("Parliament", "Temasek", "GIC", "MAS"),
    ),
    "PSE": CountryInfo(
        "Palestine", "ps",
        capital="Ramallah",
        leader_titles=("President", "Prime Minister"),
        key_ministries=(),
        regions=("West Bank", "Gaza", "Gaza Strip"),
        demonyms=("Palestinian", "Palestinians"),
        aliases=("Palestine", "State of Palestine", "Palestinian Territories"),
        major_cities=("Ramallah", "Gaza City", "Nablus", "Hebron", "Bethlehem", "Jenin"),
        key_entities=("Palestinian Authority", "PA", "PLO", "Hamas", "Fatah"),
    ),
    "LBN": CountryInfo(
        "Lebanon", "lb",
        capital="Beirut",
        leader_titles=("President", "Prime Minister"),
        key_ministries=(),
        regions=(),
        demonyms=("Lebanese",),
        aliases=("Lebanon", "Republic of Lebanon"),
        major_cities=("Beirut", "Tripoli", "Sidon"),
        key_entities=("Parliament", "Hezbollah", "Lebanese Armed Forces"),
    ),
    "SYR": CountryInfo(
        "Syria", "sy",
        capital="Damascus",
        leader_titles=("President",),
        key_ministries=(),
        regions=("Aleppo", "Idlib", "Homs", "Latakia"),
        demonyms=("Syrian", "Syrians"),
        aliases=("Syria", "Syrian Arab Republic"),
        major_cities=("Damascus", "Aleppo", "Homs"),
        key_entities=(),
    ),
    "IRQ": CountryInfo(
        "Iraq", "iq",
        capital="Baghdad",
        leader_titles=("Prime Minister", "President"),
        key_ministries=(),
        regions=("Kurdistan", "Anbar", "Basra", "Nineveh"),
        demonyms=("Iraqi", "Iraqis"),
        aliases=("Iraq", "Republic of Iraq"),
        major_cities=("Baghdad", "Basra", "Erbil", "Mosul", "Kirkuk"),
        key_entities=("Council of Representatives", "KRG", "Peshmerga"),
    ),
    "AFG": CountryInfo(
        "Afghanistan", "af",
        capital="Kabul",
        leader_titles=("Supreme Leader",),
        key_ministries=(),
        regions=("Kandahar", "Herat", "Helmand", "Nangarhar"),
        demonyms=("Afghan", "Afghans"),
        aliases=("Afghanistan", "Islamic Emirate of Afghanistan"),
        major_cities=("Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad"),
        key_entities=("Taliban",),
    ),
    "SDN": CountryInfo(
        "Sudan", "sd",
        capital="Khartoum",
        leader_titles=("Chairman",),
        key_ministries=(),
        regions=("Darfur", "Kordofan", "Blue Nile"),
        demonyms=("Sudanese",),
        aliases=("Sudan", "Republic of the Sudan"),
        major_cities=("Khartoum", "Omdurman", "Port Sudan"),
        key_entities=("SAF", "Sudanese Armed Forces", "RSF", "Rapid Support Forces"),
    ),
    "ETH": CountryInfo(
        "Ethiopia", "et",
        capital="Addis Ababa",
        leader_titles=("Prime Minister", "President"),
        key_ministries=(),
        regions=("Tigray", "Amhara", "Oromia", "Somali Region"),
        demonyms=("Ethiopian", "Ethiopians"),
        aliases=("Ethiopia", "Federal Democratic Republic of Ethiopia"),
        major_cities=("Addis Ababa",),
        key_entities=("House of Peoples' Representatives",),
    ),
    "MMR": CountryInfo(
        "Myanmar", "mm",
        capital="Naypyidaw",
        leader_titles=("Chairman",),
        key_ministries=(),
        regions=("Shan State", "Kachin State", "Rakhine State", "Karen State"),
        demonyms=("Burmese", "Myanmar"),
        aliases=("Myanmar", "Burma", "Republic of the Union of Myanmar"),
        major_cities=("Naypyidaw", "Yangon", "Mandalay"),
        key_entities=("Tatmadaw", "NUG", "National Unity Government"),
    ),
    "TWN": CountryInfo(
        "Taiwan", "tw",
        capital="Taipei",
        leader_titles=("President",),
        key_ministries=("Ministry of Foreign Affairs", "Ministry of National Defense"),
        regions=(),
        demonyms=("Taiwanese",),
        aliases=("Taiwan", "Republic of China", "ROC"),
        major_cities=("Taipei", "Kaohsiung", "Taichung", "Tainan"),
        key_entities=("Legislative Yuan", "TSMC"),
    ),
    "NLD": CountryInfo(
        "Netherlands", "nl",
        capital="Amsterdam",
        leader_titles=("Prime Minister", "King"),
        key_ministries=("Ministry of Foreign Affairs",),
        regions=("North Holland", "South Holland", "Utrecht"),
        demonyms=("Dutch",),
        aliases=("Netherlands", "Holland", "The Netherlands"),
        major_cities=("Amsterdam", "Rotterdam", "The Hague", "Utrecht"),
        key_entities=("States General", "ASML"),
    ),

    # ── STANDARD COUNTRIES (bare-minimum metadata) ────────────────────────
    "ALB": CountryInfo("Albania", "al"),
    "DZA": CountryInfo("Algeria", "dz"),
    "AND": CountryInfo("Andorra", "ad"),
    "AGO": CountryInfo("Angola", "ao"),
    "ATG": CountryInfo("Antigua and Barbuda", "ag"),
    "ARM": CountryInfo("Armenia", "am"),
    "AUT": CountryInfo("Austria", "at"),
    "AZE": CountryInfo("Azerbaijan", "az"),
    "BHS": CountryInfo("Bahamas", "bs"),
    "BHR": CountryInfo("Bahrain", "bh"),
    "BGD": CountryInfo("Bangladesh", "bd"),
    "BRB": CountryInfo("Barbados", "bb"),
    "BLR": CountryInfo("Belarus", "by"),
    "BEL": CountryInfo("Belgium", "be"),
    "BLZ": CountryInfo("Belize", "bz"),
    "BEN": CountryInfo("Benin", "bj"),
    "BTN": CountryInfo("Bhutan", "bt"),
    "BOL": CountryInfo("Bolivia", "bo"),
    "BIH": CountryInfo("Bosnia and Herzegovina", "ba"),
    "BWA": CountryInfo("Botswana", "bw"),
    "BRN": CountryInfo("Brunei", "bn"),
    "BGR": CountryInfo("Bulgaria", "bg"),
    "BFA": CountryInfo("Burkina Faso", "bf"),
    "BDI": CountryInfo("Burundi", "bi"),
    "KHM": CountryInfo("Cambodia", "kh"),
    "CMR": CountryInfo("Cameroon", "cm"),
    "CPV": CountryInfo("Cape Verde", "cv"),
    "CAF": CountryInfo("Central African Republic", "cf"),
    "TCD": CountryInfo("Chad", "td"),
    "CHL": CountryInfo("Chile", "cl"),
    "COM": CountryInfo("Comoros", "km"),
    "COG": CountryInfo("Republic of the Congo", "cg"),
    "COD": CountryInfo("Democratic Republic of the Congo", "cd"),
    "CRI": CountryInfo("Costa Rica", "cr"),
    "CIV": CountryInfo("Côte d'Ivoire", "ci"),
    "HRV": CountryInfo("Croatia", "hr"),
    "CUB": CountryInfo("Cuba", "cu"),
    "CYP": CountryInfo("Cyprus", "cy"),
    "CZE": CountryInfo("Czech Republic", "cz"),
    "DNK": CountryInfo("Denmark", "dk"),
    "DJI": CountryInfo("Djibouti", "dj"),
    "DMA": CountryInfo("Dominica", "dm"),
    "DOM": CountryInfo("Dominican Republic", "do"),
    "ECU": CountryInfo("Ecuador", "ec"),
    "SLV": CountryInfo("El Salvador", "sv"),
    "GNQ": CountryInfo("Equatorial Guinea", "gq"),
    "ERI": CountryInfo("Eritrea", "er"),
    "EST": CountryInfo("Estonia", "ee"),
    "SWZ": CountryInfo("Eswatini", "sz"),
    "FJI": CountryInfo("Fiji", "fj"),
    "FIN": CountryInfo("Finland", "fi"),
    "GAB": CountryInfo("Gabon", "ga"),
    "GMB": CountryInfo("Gambia", "gm"),
    "GEO": CountryInfo("Georgia", "ge"),
    "GHA": CountryInfo("Ghana", "gh"),
    "GRC": CountryInfo("Greece", "gr"),
    "GRD": CountryInfo("Grenada", "gd"),
    "GTM": CountryInfo("Guatemala", "gt"),
    "GIN": CountryInfo("Guinea", "gn"),
    "GNB": CountryInfo("Guinea-Bissau", "gw"),
    "GUY": CountryInfo("Guyana", "gy"),
    "HTI": CountryInfo("Haiti", "ht"),
    "HND": CountryInfo("Honduras", "hn"),
    "HUN": CountryInfo("Hungary", "hu"),
    "ISL": CountryInfo("Iceland", "is"),
    "JAM": CountryInfo("Jamaica", "jm"),
    "JOR": CountryInfo("Jordan", "jo"),
    "KAZ": CountryInfo("Kazakhstan", "kz"),
    "KEN": CountryInfo("Kenya", "ke"),
    "KIR": CountryInfo("Kiribati", "ki"),
    "KWT": CountryInfo("Kuwait", "kw"),
    "KGZ": CountryInfo("Kyrgyzstan", "kg"),
    "LAO": CountryInfo("Laos", "la"),
    "LVA": CountryInfo("Latvia", "lv"),
    "LSO": CountryInfo("Lesotho", "ls"),
    "LBR": CountryInfo("Liberia", "lr"),
    "LBY": CountryInfo("Libya", "ly"),
    "LIE": CountryInfo("Liechtenstein", "li"),
    "LTU": CountryInfo("Lithuania", "lt"),
    "LUX": CountryInfo("Luxembourg", "lu"),
    "MDG": CountryInfo("Madagascar", "mg"),
    "MWI": CountryInfo("Malawi", "mw"),
    "MDV": CountryInfo("Maldives", "mv"),
    "MLI": CountryInfo("Mali", "ml"),
    "MLT": CountryInfo("Malta", "mt"),
    "MHL": CountryInfo("Marshall Islands", "mh"),
    "MRT": CountryInfo("Mauritania", "mr"),
    "MUS": CountryInfo("Mauritius", "mu"),
    "FSM": CountryInfo("Micronesia", "fm"),
    "MDA": CountryInfo("Moldova", "md"),
    "MCO": CountryInfo("Monaco", "mc"),
    "MNG": CountryInfo("Mongolia", "mn"),
    "MNE": CountryInfo("Montenegro", "me"),
    "MAR": CountryInfo("Morocco", "ma"),
    "MOZ": CountryInfo("Mozambique", "mz"),
    "NAM": CountryInfo("Namibia", "na"),
    "NRU": CountryInfo("Nauru", "nr"),
    "NPL": CountryInfo("Nepal", "np"),
    "NZL": CountryInfo("New Zealand", "nz"),
    "NIC": CountryInfo("Nicaragua", "ni"),
    "NER": CountryInfo("Niger", "ne"),
    "MKD": CountryInfo("North Macedonia", "mk"),
    "NOR": CountryInfo("Norway", "no"),
    "OMN": CountryInfo("Oman", "om"),
    "PLW": CountryInfo("Palau", "pw"),
    "PAN": CountryInfo("Panama", "pa"),
    "PNG": CountryInfo("Papua New Guinea", "pg"),
    "PRY": CountryInfo("Paraguay", "py"),
    "PER": CountryInfo("Peru", "pe"),
    "PRT": CountryInfo("Portugal", "pt"),
    "QAT": CountryInfo("Qatar", "qa"),
    "ROU": CountryInfo("Romania", "ro"),
    "RWA": CountryInfo("Rwanda", "rw"),
    "KNA": CountryInfo("Saint Kitts and Nevis", "kn"),
    "LCA": CountryInfo("Saint Lucia", "lc"),
    "VCT": CountryInfo("Saint Vincent and the Grenadines", "vc"),
    "WSM": CountryInfo("Samoa", "ws"),
    "SMR": CountryInfo("San Marino", "sm"),
    "STP": CountryInfo("São Tomé and Príncipe", "st"),
    "SEN": CountryInfo("Senegal", "sn"),
    "SRB": CountryInfo("Serbia", "rs"),
    "SYC": CountryInfo("Seychelles", "sc"),
    "SLE": CountryInfo("Sierra Leone", "sl"),
    "SVK": CountryInfo("Slovakia", "sk"),
    "SVN": CountryInfo("Slovenia", "si"),
    "SLB": CountryInfo("Solomon Islands", "sb"),
    "SOM": CountryInfo("Somalia", "so"),
    "SSD": CountryInfo("South Sudan", "ss"),
    "LKA": CountryInfo("Sri Lanka", "lk"),
    "SUR": CountryInfo("Suriname", "sr"),
    "SWE": CountryInfo("Sweden", "se"),
    "CHE": CountryInfo("Switzerland", "ch"),
    "TJK": CountryInfo("Tajikistan", "tj"),
    "TZA": CountryInfo("Tanzania", "tz"),
    "TLS": CountryInfo("Timor-Leste", "tl"),
    "TGO": CountryInfo("Togo", "tg"),
    "TON": CountryInfo("Tonga", "to"),
    "TTO": CountryInfo("Trinidad and Tobago", "tt"),
    "TUN": CountryInfo("Tunisia", "tn"),
    "TKM": CountryInfo("Turkmenistan", "tm"),
    "TUV": CountryInfo("Tuvalu", "tv"),
    "UGA": CountryInfo("Uganda", "ug"),
    "URY": CountryInfo("Uruguay", "uy"),
    "UZB": CountryInfo("Uzbekistan", "uz"),
    "VUT": CountryInfo("Vanuatu", "vu"),
    "VAT": CountryInfo("Vatican City", "va"),
    "VEN": CountryInfo("Venezuela", "ve"),
    "YEM": CountryInfo("Yemen", "ye"),
    "ZMB": CountryInfo("Zambia", "zm"),
    "ZWE": CountryInfo("Zimbabwe", "zw"),
    # Territories and special regions
    "XKX": CountryInfo("Kosovo", "xk"),
    "GRL": CountryInfo("Greenland", "gl"),
    "NCL": CountryInfo("New Caledonia", "nc"),
    "PRI": CountryInfo("Puerto Rico", "pr"),
    "GUF": CountryInfo("French Guiana", "gf"),
    "REU": CountryInfo("Réunion", "re"),
    "MTQ": CountryInfo("Martinique", "mq"),
    "GLP": CountryInfo("Guadeloupe", "gp"),
    "MYT": CountryInfo("Mayotte", "yt"),
    "HKG": CountryInfo("Hong Kong", "hk"),
    "MAC": CountryInfo("Macau", "mo"),
    "FLK": CountryInfo("Falkland Islands", "fk"),
    "FRO": CountryInfo("Faroe Islands", "fo"),
    "SJM": CountryInfo("Svalbard and Jan Mayen", "sj"),
    "CUW": CountryInfo("Curaçao", "cw"),
    "ABW": CountryInfo("Aruba", "aw"),
    "SXM": CountryInfo("Sint Maarten", "sx"),
    "CYM": CountryInfo("Cayman Islands", "ky"),
    "BMU": CountryInfo("Bermuda", "bm"),
    "GIB": CountryInfo("Gibraltar", "gi"),
    "TCA": CountryInfo("Turks and Caicos Islands", "tc"),
    "VGB": CountryInfo("British Virgin Islands", "vg"),
    "AIA": CountryInfo("Anguilla", "ai"),
    "MSR": CountryInfo("Montserrat", "ms"),
    "SHN": CountryInfo("Saint Helena", "sh"),
    "WLF": CountryInfo("Wallis and Futuna", "wf"),
    "SPM": CountryInfo("Saint Pierre and Miquelon", "pm"),
    "PCN": CountryInfo("Pitcairn Islands", "pn"),
}

# Legacy compat — flat dict for quick name lookups
COUNTRY_LOOKUP: dict[str, str] = {code: info.name for code, info in COUNTRIES.items()}


def get_country_name(iso_a3: str) -> str:
    """Return the display name for an ISO_A3 code, or the code itself as fallback."""
    info = COUNTRIES.get(iso_a3.upper())
    return info.name if info else iso_a3


def get_iso_a2(iso_a3: str) -> str:
    """Return the ISO_A2 code for news API queries. Falls back to lowercase A3 slice."""
    info = COUNTRIES.get(iso_a3.upper())
    if info:
        return info.iso_a2
    fallback = (iso_a3[0] + iso_a3[1]) if len(iso_a3) >= 2 else iso_a3
    return fallback.lower()


def get_country_info(iso_a3: str) -> CountryInfo | None:
    """Return the full CountryInfo for an ISO_A3 code, or None."""
    return COUNTRIES.get(iso_a3.upper())
